# Generated by Django 6.0.4 on 2026-04-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=10, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('temp', models.FloatField(default=0.0)),
                ('ph', models.FloatField(default=0.0)),
                ('stage', models.CharField(default='Initial', max_length=50)),
                ('is_motor_active', models.BooleanField(default=False)),
            ],
        ),
    ]
