# Generated by Django 6.0.4 on 2026-04-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermentation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='batch_id',
            new_name='batch_number',
        ),
        migrations.AddField(
            model_name='batch',
            name='gas_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='ph',
            field=models.FloatField(default=7.0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='stage',
            field=models.CharField(default='INITIAL', max_length=50),
        ),
    ]
